import "~/styles/globals.css";

import { type Metadata } from "next";
import { Inter } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Suspense } from "react";
import { ApiProvider } from "~/components/providers/api-provider";
import { ThemeProvider } from "~/components/providers/theme-provider";
import { TailwindIndicator } from "~/components/ui/tailwind-indicator";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`} suppressHydrationWarning>
      <body className="flex min-h-dvh flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ApiProvider>
            <NuqsAdapter>
              {/* TODO: Add Suspense fallback */}
              <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
              <TailwindIndicator />
            </NuqsAdapter>
          </ApiProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
